<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="softHardAssert.AssertEx" tests="1" time="0.008" ignored="3" failures="1" timestamp="16 Jul 2021 04:08:05 GMT" skipped="0" hostname="Kalyani" errors="0">
  <testcase name="softAssertEx" time="0.008" classname="softHardAssert.AssertEx">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [1] but found [0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at softHardAssert.AssertEx.softAssertEx(AssertEx.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- softAssertEx -->
  <testcase name="aSoftAssert" classname="softHardAssert.AssertEx">
    <skipped/>
  </testcase> <!-- aSoftAssert -->
  <testcase name="softAssert" classname="softHardAssert.AssertEx">
    <skipped/>
  </testcase> <!-- softAssert -->
  <testcase name="hardAssert" classname="softHardAssert.AssertEx">
    <skipped/>
  </testcase> <!-- hardAssert -->
</testsuite> <!-- softHardAssert.AssertEx -->
